# Generated by Django 4.1.4 on 2022-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Sarlavha')),
                ('description', models.TextField(unique=True, verbose_name='Mazmuni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('publish', models.BooleanField(default=True, verbose_name='Nashr etilganligi')),
            ],
        ),
    ]
